# Generated by Django 5.0.7 on 2024-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Value', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('available', models.BooleanField()),
            ],
        ),
    ]
